name: "autobuild"
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set output
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Install dependencies
        run: go get .

      - name: Build
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          go version
          pwd
          GOOS=linux GOARCH=amd64 go build -ldflags="-s -w -X 'main.Version=${RELEASE_VERSION}'" -o builds/branch-changer-linux-amd64 .
          GOOS=darwin GOARCH=arm64 go build -ldflags="-s -w -X 'main.Version=${RELEASE_VERSION}'" -o builds/branch-changer-darwin-arm64 .
          ls -lah builds

      - name: Extract release notes
        id: extract-release-notes
        uses: ffurrer2/extract-release-notes@v1

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body: ${{ steps.extract-release-notes.outputs.release_notes }}
          files: |
            builds/branch-changer-linux-amd64
            builds/branch-changer-darwin-arm64
          draft: false
          prerelease: false
